name: flutter_paytm_ui
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: "^0.4.5"
  carousel_slider: any
  flutter_swiper : ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/paytm_logo.png
  - assets/uanotif_nomessage.png
  - assets/smartphone.png
  - assets/hand.png
  - assets/phone-charge.png
  - assets/gold.png
  - assets/iocl_tip.png
  - assets/train_help.png
  - assets/send_money.png
  - assets/money_transfer.png
  - assets/ic_passbook_header.png
  - assets/calendar_blue.png
  - assets/add_money_passbook.png
  - assets/book.png
  - assets/real.jpg
  - assets/gstbanner.png
  - assets/logo.png
  - assets/powered_by.png
  - assets/shopping-bagg.png
  - assets/shopping-bag.png
  - assets/satellite-dish.png
  - assets/qr-code.png
  - assets/delivery.png
  - assets/console.png
  - assets/bank.png
  - assets/airplane.png
  - assets/access.png
  - assets/placeholder_inapp_merchants.png
  - assets/home.png
  - assets/right-arrow.png
